# Regressão Linear simples

A base foi gerada aleatória, e esse é apenas um exemplo simples da implementação.

In [44]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Carregar a base de dados

In [47]:
bd = pd.read_csv("db.csv", delimiter=";", nrows=20)
bd

Salario  Idade   Custo
0    2337.27     51  119.20
1    2561.70     49  125.52
2   11652.21     23  268.00
3    8274.59     45  372.36
4    9952.98     28  278.68
5    6637.47     55  365.06
6   10387.27     51  529.75
7    5513.91     51  281.21
8    7953.64     59  469.26
9   10023.61     43  431.02
10   2621.11     27   70.77
11  10853.20     54  586.07
12   7640.32     57  435.50
13   9726.02     30  291.78
14   6311.98     26  164.11
15   3175.73     62  196.90
16  10414.09     20  208.28
17   3754.11     18   67.57
18  10000.25     59  590.01
19   3250.22     19   61.75

In [48]:
# Observar os dados
# Outras analises podem ser feitas
bd.describe()

Salario      Idade       Custo
count     20.000000  20.000000   20.000000
mean    7152.084000  41.350000  295.640000
std     3236.676572  15.526802  171.351199
min     2337.270000  18.000000   61.750000
25%     3628.137500  26.750000  154.462500
50%     7796.980000  47.000000  279.945000
75%    10006.090000  54.250000  432.140000
max    11652.210000  62.000000  590.010000

# Agora é separar a base em X e Y

In [49]:
x = bd.iloc[:,0].values # Nesse caso, estou levando em consideração só a coluna de salario
y = bd.iloc[:,2].values # Aqui a coluna que quero prever, no caso a de custo

In [50]:
# Visualizando x e y
# display(x)
display(y)

array([119.2 , 125.52, 268.  , 372.36, 278.68, 365.06, 529.75, 281.21,
       469.26, 431.02,  70.77, 586.07, 435.5 , 291.78, 164.11, 196.9 ,
       208.28,  67.57, 590.01,  61.75])

In [51]:
# Vamos ver a correlação entre as colunas
np.corrcoef(x, y)

array([[1.        , 0.73206591],
       [0.73206591, 1.        ]])

# Precisamos fazer o reshape do X antes de enviar para o Sklearn

In [53]:
x = x.reshape(-1, 1)
x

array([[ 2337.27],
       [ 2561.7 ],
       [11652.21],
       [ 8274.59],
       [ 9952.98],
       [ 6637.47],
       [10387.27],
       [ 5513.91],
       [ 7953.64],
       [10023.61],
       [ 2621.11],
       [10853.2 ],
       [ 7640.32],
       [ 9726.02],
       [ 6311.98],
       [ 3175.73],
       [10414.09],
       [ 3754.11],
       [10000.25],
       [ 3250.22]])

# Vamos separar a base de treino e teste

In [54]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.33, random_state=30)

# Vamos treinar o modelo

In [58]:
regressor = LinearRegression()
regressor.fit(x_treino, y_treino)

regressor.score(x_teste, y_teste)
previsao = regressor.predict(x_teste)

# Vamos observar o modelo através de um gráfico

In [60]:
grafico = px.scatter(x=x.ravel(), y=y)
grafico.add_scatter(x=x_teste.ravel(), y=previsao)
grafico.show()