# Regressão Linear simples

A base foi gerada aleatória, e esse é apenas um exemplo simples da implementação.

In [22]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Carregar a base de dados

In [23]:
bd = pd.read_csv("db.csv", delimiter=";", nrows=25)
bd

Salario  Idade   Custo
0   11177.78     23  748.27
1    2633.90     59  196.82
2   11026.95     49  804.84
3    6739.66     49  462.12
4    9799.03     48  692.70
5    2520.08     28  181.86
6    1536.44     22  111.79
7    9299.25     41  743.40
8   11487.56     43  819.04
9    3389.47     23  213.46
10   2876.39     46  231.55
11   3181.83     47  246.92
12  11431.13     44  882.67
13   3270.25     58  224.06
14  10872.05     51  701.65
15  10383.22     29  761.58
16   6113.69     45  479.88
17   8975.79     37  715.11
18   8837.50     21  650.09
19   2896.92     34  232.70
20   2417.69     45  168.13
21  10394.05     35  796.67
22   2373.24     21  153.45
23  10739.36     41  818.07
24   3444.25     49  214.71

In [24]:
# Observar os dados
# Outras analises podem ser feitas
bd.describe()

Salario      Idade       Custo
count     25.000000  25.000000   25.000000
mean    6712.699200  39.520000  490.061600
std     3785.781008  11.597845  280.392484
min     1536.440000  21.000000  111.790000
25%     2896.920000  29.000000  214.710000
50%     6739.660000  43.000000  479.880000
75%    10394.050000  48.000000  748.270000
max    11487.560000  59.000000  882.670000

# Agora é separar a base em X e Y

In [25]:
x = bd.iloc[:,0].values # Nesse caso, estou levando em consideração só a coluna de salario
y = bd.iloc[:,2].values # Aqui a coluna que quero prever, no caso a de custo

In [26]:
# Visualizando x e y
# display(x)
display(y)

array([748.27, 196.82, 804.84, 462.12, 692.7 , 181.86, 111.79, 743.4 ,
       819.04, 213.46, 231.55, 246.92, 882.67, 224.06, 701.65, 761.58,
       479.88, 715.11, 650.09, 232.7 , 168.13, 796.67, 153.45, 818.07,
       214.71])

In [27]:
# Vamos ver a correlação entre as colunas
np.corrcoef(x, y)

array([[1.        , 0.99122941],
       [0.99122941, 1.        ]])

# Precisamos fazer o reshape do X antes de enviar para o Sklearn

In [28]:
x = x.reshape(-1, 1)
x

array([[11177.78],
       [ 2633.9 ],
       [11026.95],
       [ 6739.66],
       [ 9799.03],
       [ 2520.08],
       [ 1536.44],
       [ 9299.25],
       [11487.56],
       [ 3389.47],
       [ 2876.39],
       [ 3181.83],
       [11431.13],
       [ 3270.25],
       [10872.05],
       [10383.22],
       [ 6113.69],
       [ 8975.79],
       [ 8837.5 ],
       [ 2896.92],
       [ 2417.69],
       [10394.05],
       [ 2373.24],
       [10739.36],
       [ 3444.25]])

# Vamos separar a base de treino e teste

In [29]:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.33, random_state=30)

# Vamos treinar o modelo

In [30]:
regressor = LinearRegression()
regressor.fit(x_treino, y_treino)

regressor.score(x_teste, y_teste)
previsao = regressor.predict(x_teste)

# Vamos observar o modelo através de um gráfico

In [31]:
grafico = px.scatter(x=x.ravel(), y=y)
grafico.add_scatter(x=x_teste.ravel(), y=previsao, name="Linha de regressão")
grafico.show()